spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toylocal?serverTimezone=UTC&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

jwt:
  jks:
    fileName: toylocal.jks
    alias: toylocal
    pass: abc123